[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "isort>=6.0.1",
    "scalar-fastapi>=1.2.2",
    "tensorflow>=2.19.0",
    "uvicorn>=0.35.0",
]
